import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={ {
      color: 'white',
      overflow:'auto',
    }}>
      <body style={ {
        background: '#111',
        display: 'flex',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
      }}>{children}</body>
    </html>
  )
}
