export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={ {
      background: 'black',
      color: 'white',
    }}>
      <body>{children}</body>
    </html>
  )
}
